import 'package:flutter/material.dart';
import '../services/recipe_service.dart';
import 'recipe_details_screen.dart';

class IngredientSelectionScreen extends StatefulWidget {
  const IngredientSelectionScreen({Key? key}) : super(key: key);

  @override
  State<IngredientSelectionScreen> createState() =>
      _IngredientSelectionScreenState();
}

class _IngredientSelectionScreenState extends State<IngredientSelectionScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  final Set<String> _selectedIngredients = {};
  final TextEditingController _searchController = TextEditingController();
  String _searchQuery = '';

  final List<String> _categories = [
    'Pantry Essentials',
    'Vegetables & Greens',
    'Mushrooms',
    'Fruits',
    'Berries',
    'Nuts & Seeds',
    'Cheese',
    'Dairy & Eggs',
    'Dairy Free & Meat Substitutes',
    'Meats',
    'Poultry',
    'Fish & Seafood',
    'Herbs & Spices',
    'Sugar & Sweeteners',
    'Seasonings & Spice Blends',
    'Baking',
    'Pre-made Doughs & Wrappers',
    'Grains & Cereals',
    'Legumes',
    'Pasta',
    'Bread & Salty Snacks',
    'Oils & Fats',
    'Dressings & Vinegars',
    'Condiments',
    'Canned Food',
    'Sauces, Spreads & Dips',
    'Soups, Stews & Stocks',
    'Desserts & Sweet Snacks',
    'Wine, Beer & Spirits',
    'Beverages',
    'Supplements & Extracts',
  ];

  final Map<String, List<String>> _categoryIngredients = {
    'Pantry Essentials': [
      'Flour',
      'Sugar',
      'Salt',
      'Pepper',
      'Rice',
      'Pasta',
      'Olive Oil',
      'Vinegar',
      'Baking Powder',
      'Baking Soda',
      'Cornstarch',
      'Honey',
      'Maple Syrup',
      'Soy Sauce',
      'Coconut Milk',
      'Peanut Butter',
      'Vegetable Oil',
      'Sesame Oil',
      'Canned Tomatoes',
      'Canned Beans',
      'Canned Coconut Milk',
      'Dried Herbs',
      'Dried Fruits',
      'Instant Oats',
      'Granola',
      'Rice Vinegar',
      'Fish Sauce',
      'Mustard',
      'Ketchup',
      'Mayonnaise',
      'Hot Sauce',
      'Taco Seasoning',
      'Italian Seasoning',
      'Curry Powder',
      'Chili Powder',
      'Garlic Powder',
      'Onion Powder',
      'Paprika',
      'Cinnamon',
      'Nutmeg',
      'Allspice',
      'Cloves',
      'Vanilla Extract',
      'Almond Extract',
      'Lemon Juice',
      'Lime Juice',
      'Balsamic Vinegar',
      'Apple Cider Vinegar',
      'Poppy Seeds',
      'Sesame Seeds',
      'Chia Seeds',
      'Flaxseeds',
      'Quinoa',
      'Couscous',
      'Barley',
      'Farro',
      'Polenta',
      'Cornmeal',
      'Tapioca',
      'Gelatin',
      'Pudding Mix',
      'Cake Mix',
      'Brownie Mix',
      'Chocolate Chips',
      'Cocoa Powder',
      'Yeast',
      'Bread Crumbs',
      'Pasta Sauce',
      'Salsa',
      'Pickles',
      'Olives',
      'Capers',
      'Sun-Dried Tomatoes',
      'Nutritional Yeast',
      'Coconut Flour',
      'Almond Flour',
      'Rice Flour',
      'Tapioca Flour',
      'Potato Starch',
      'Arrowroot Powder',
      'Coconut Sugar',
      'Brown Rice',
      'White Rice',
      'Wild Rice',
      'Jasmine Rice',
      'Basmati Rice',
      'Puffed Rice',
      'Rice Cakes',
      'Corn Tortillas',
      'Flour Tortillas',
      'Pita Bread',
      'Naan',
      'Bagels',
      'English Muffins',
      'Tortilla Chips',
      'Crackers',
      'Pretzels',
      'Popcorn',
      'Rice Noodles',
      'Soba Noodles',
      'Udon Noodles',
      'Egg Noodles',
      'Zoodles',
      'Spaghetti Squash',
      'Chickpea Pasta',
    ],
    'Vegetables & Greens': [
      'Carrots',
      'Broccoli',
      'Spinach',
      'Lettuce',
      'Tomatoes',
      'Cucumber',
      'Bell Peppers',
      'Onions',
      'Garlic',
      'Zucchini',
      'Cauliflower',
      'Kale',
      'Swiss Chard',
      'Asparagus',
      'Brussels Sprouts',
      'Eggplant',
      'Radishes',
      'Beets',
      'Sweet Potatoes',
      'Potatoes',
      'Green Beans',
      'Peas',
      'Artichokes',
      'Leeks',
      'Celery',
      'Cabbage',
      'Mushrooms',
      'Pumpkin',
      'Squash',
      'Chard',
      'Arugula',
      'Endive',
      'Fennel',
      'Bok Choy',
      'Collard Greens',
      'Mustard Greens',
      'Turnips',
      'Parsnips',
      'Jicama',
      'Chayote',
      'Seaweed',
      'Nori',
      'Kelp',
      'Mizuna',
      'Watercress',
      'Radicchio',
      'Savoy Cabbage',
      'Fiddleheads',
      'Celeriac',
      'Daikon',
      'Taro',
      'Sunchokes',
      'Chervil',
      'Sorrel',
      'Tarragon',
      'Chives',
      'Scallions',
      'Shallots',
      'Fennel Fronds',
      'Cilantro',
      'Parsley',
      'Dill',
      'Basil',
      'Mint',
      'Oregano',
      'Thyme',
      'Sage',
      'Rosemary',
      'Bay Leaves',
      'Chili Peppers',
      'Habanero',
      'Serrano',
      'Jalapeño',
      'Poblano',
      'Anaheim',
      'Ghost Pepper',
      'Bell Pepper',
      'Cubanelle',
      'Banana Peppers',
      'Peppadew',
      'Fresno Peppers',
      'Cayenne Pepper',
      'Paprika',
      'Black Olives',
      'Green Olives',
      'Kalamata Olives',
      'Capers',
      'Pickled Vegetables',
      'Sauerkraut',
      'Kimchi',
      'Fermented Vegetables',
    ],
    'Mushrooms': [
      'Button Mushrooms',
      'Portobello',
      'Shiitake',
      'Oyster Mushrooms',
      'Cremini',
      'Enoki',
      'Maitake',
      'Chanterelle',
      'Porcini',
      'Morel',
      'Lion’s Mane',
      'Shimeji',
      'Wood Ear',
      'Cordyceps',
      'Reishi',
      'Turkey Tail',
      'Tremella',
      'Black Fungus',
      'Matsutake',
      'King Oyster',
      'Beech Mushrooms',
      'Pioppino',
      'Hedgehog Mushrooms',
      'Chaga',
      'Cordyceps Militaris',
      'Puffball Mushrooms',
      'Giant Puffball',
      'Fairy Ring Mushrooms',
      'Saffron Milk Cap',
      'Cauliflower Mushroom',
      'Chicken of the Woods',
      'Hen of the Woods',
      'Shaggy Mane',
      'St. George’s Mushroom',
      'Lobster Mushroom',
      'Truffle',
      'Black Truffle',
      'White Truffle',
      'Summer Truffle',
      'Winter Truffle',
    ],
    'Fruits': [
      'Apples',
      'Bananas',
      'Oranges',
      'Grapes',
      'Mangoes',
      'Pineapple',
      'Strawberries',
      'Blueberries',
      'Raspberries',
      'Blackberries',
      'Peaches',
      'Plums',
      'Cherries',
      'Kiwifruit',
      'Pears',
      'Watermelon',
      'Cantaloupe',
      'Honeydew',
      'Papaya',
      'Passion Fruit',
      'Dragon Fruit',
      'Lychee',
      'Starfruit',
      'Persimmon',
      'Pomegranate',
      'Coconut',
      'Tangerines',
      'Mandarins',
      'Nectarines',
      'Apricots',
      'Figs',
      'Dates',
      'Rhubarb',
      'Gooseberries',
      'Currants',
      'Mulberries',
      'Quince',
      'Soursop',
      'Jackfruit',
      'Durian',
      'Bitter Melon',
      'Cranberries',
      'Acai Berries',
      'Elderberries',
      'Sea Buckthorn',
      'Bilberries',
      'Cloudberries',
      'Salak',
      'Longan',
      'Rambutan',
      'Sapodilla',
      'Jabuticaba',
      'Miracle Fruit',
      'Cupuacu',
      'Buddha’s Hand',
      'Calamondin',
      'Kumquat',
      'Yuzu',
      'Bergamot',
      'Finger Lime',
      'Bitter Orange',
      'Sweet Lemon',
      'Sweet Lime',
    ],
    'Berries': [
      'Strawberries',
      'Blueberries',
      'Raspberries',
      'Blackberries',
      'Cranberries',
      'Gooseberries',
      'Elderberries',
      'Acai Berries',
      'Mulberries',
      'Boysenberries',
      'Marionberries',
      'Loganberries',
      'Cloudberries',
      'Huckleberries',
      'Salmonberries',
      'Thimbleberries',
      'Wineberries',
      'Dewberries',
      'Serviceberries',
      'Jostaberries',
      'Barberries',
      'Lingonberries',
      'Bilberries',
      'Saskatoon Berries',
      'Chokecherries',
      'Sea Buckthorn Berries',
      'Black Currants',
      'Red Currants',
      'White Currants',
      'Golden Raspberries',
      'Pink Raspberries',
      'Black Raspberries',
      'Yellow Raspberries',
      'Tayberries',
      'Dewberries',
      'Marionberries',
      'Salmonberries',
      'Thimbleberries',
      'Wineberries',
      'Huckleberries',
      'Serviceberries',
      'Jostaberries',
      'Barberries',
      'Lingonberries',
      'Bilberries',
      'Saskatoon Berries',
      'Chokecherries',
      'Sea Buckthorn Berries',
      'Black Currants',
      'Red Currants',
      'White Currants',
      'Golden Raspberries',
      'Pink Raspberries',
      'Black Raspberries',
      'Yellow Raspberries',
      'Tayberries',
    ],
    'Nuts & Seeds': [
      'Almonds',
      'Walnuts',
      'Peanuts',
      'Sunflower Seeds',
      'Pumpkin Seeds',
      'Pistachios',
      'Cashews',
      'Hazelnuts',
      'Brazil Nuts',
      'Macadamia Nuts',
      'Pine Nuts',
      'Chia Seeds',
      'Flaxseeds',
      'Sesame Seeds',
      'Hemp Seeds',
      'Poppy Seeds',
      'Coconut Flakes',
      'Coconut Chips',
      'Nut Butters',
      'Peanut Butter',
      'Almond Butter',
      'Cashew Butter',
      'Sunflower Seed Butter',
      'Tahini',
      'Nut Milk',
      'Almond Milk',
      'Cashew Milk',
      'Coconut Milk',
      'Soy Milk',
      'Oat Milk',
      'Rice Milk',
      'Hazelnut Milk',
      'Pistachio Milk',
      'Pumpkin Seed Milk',
      'Flax Milk',
      'Hemp Milk',
      'Peanut Milk',
      'Walnut Milk',
      'Macadamia Milk',
      'Coconut Cream',
      'Nut Cream',
      'Nut Flour',
      'Almond Flour',
      'Coconut Flour',
      'Hazelnut Flour',
      'Pecan Flour',
      'Chestnut Flour',
      'Nut Granola',
      'Nut Clusters',
      'Nut Bars',
      'Nut Snacks',
      'Nut Mixes',
      'Seed Mixes',
      'Trail Mix',
      'Granola Bars',
      'Energy Balls',
      'Protein Balls',
      'Nut Energy Bites',
    ],
    'Cheese': [
      'Cheddar',
      'Mozzarella',
      'Parmesan',
      'Feta',
      'Brie',
      'Gouda',
      'Swiss',
      'Provolone',
      'Ricotta',
      'Cream Cheese',
      'Blue Cheese',
      'Gorgonzola',
      'Camembert',
      'Havarti',
      'Colby Jack',
      'Monterey Jack',
      'Cotage Cheese',
      'Mascarpone',
      'Neufchâtel',
      'Pecorino',
      'Asiago',
      'Gruyère',
      'Emmental',
      'Queso Fresco',
      'Queso Blanco',
      'Paneer',
      'Halloumi',
      'Burrata',
      'Feta Crumbles',
      'Goat Cheese',
      'Vegan Cheese',
      'Nutritional Yeast',
      'Almond Cheese',
      'Cashew Cheese',
      'Soy Cheese',
      'Coconut Cheese',
      'Rice Cheese',
      'Pea Protein Cheese',
      'Sunflower Seed Cheese',
      'Pumpkin Seed Cheese',
      'Hemp Cheese',
      'Dairy-Free Cream Cheese',
      'Dairy-Free Ricotta',
      'Dairy-Free Mozzarella',
      'Dairy-Free Cheddar',
      'Dairy-Free Parmesan',
      'Dairy-Free Feta',
      'Dairy-Free Gouda',
      'Dairy-Free Brie',
      'Dairy-Free Blue Cheese',
    ],
    'Dairy & Eggs': [
      'Milk',
      'Eggs',
      'Butter',
      'Yogurt',
      'Cream',
      'Sour Cream',
      'Heavy Cream',
      'Half and Half',
      'Buttermilk',
      'Cottage Cheese',
      'Greek Yogurt',
      'Skyr',
      'Kefir',
      'Egg Whites',
      'Egg Yolks',
      'Liquid Eggs',
      'Powdered Eggs',
      'Egg Substitutes',
      'Plant-Based Milk',
      'Almond Milk',
      'Soy Milk',
      'Oat Milk',
      'Coconut Milk',
      'Rice Milk',
      'Cashew Milk',
      'Hemp Milk',
      'Flax Milk',
      'Pea Milk',
      'Macadamia Milk',
      'Goat Milk',
      'Sheep Milk',
      'Camel Milk',
      'Buffalo Milk',
      'Condensed Milk',
      'Evaporated Milk',
      'Dairy-Free Yogurt',
      'Dairy-Free Ice Cream',
      'Dairy-Free Cream Cheese',
      'Dairy-Free Sour Cream',
      'Dairy-Free Butter',
      'Dairy-Free Whipped Cream',
      'Dairy-Free Cheese',
      'Eggnog',
      'Custard',
      'Pudding',
      'Flan',
      'Quiche',
      'Frittata',
      'Deviled Eggs',
      'Egg Salad',
      'Omelettes',
      'Scrambled Eggs',
      'Poached Eggs',
      'Hard-Boiled Eggs',
      'Soft-Boiled Eggs',
      'Egg Drop Soup',
      'Egg Fried Rice',
      'Egg Noodles',
      'Egg Wash',
      'Egg Bakes',
      'Egg Muffins',
      'Egg Casseroles',
      'Egg Soufflés',
      'Egg Tarts',
    ],
    'Dairy Free & Meat Substitutes': [
      'Almond Milk',
      'Soy Milk',
      'Coconut Milk',
      'Oat Milk',
      'Rice Milk',
      'Hemp Milk',
      'Pea Protein',
      'Tofu',
      'Tempeh',
      'Seitan',
      'Jackfruit',
      'Mushroom Burgers',
      'Lentil Burgers',
      'Chickpea Patties',
      'Black Bean Burgers',
      'Quinoa Burgers',
      'Cauliflower Steaks',
      'Eggplant Steaks',
      'Zucchini Noodles',
      'Spaghetti Squash',
      'Vegan Sausages',
      'Vegan Bacon',
      'Vegan Cheese',
      'Vegan Sour Cream',
      'Vegan Yogurt',
      'Vegan Ice Cream',
      'Vegan Butter',
      'Vegan Cream Cheese',
      'Vegan Mayonnaise',
      'Vegan Protein Powder',
      'Nutritional Yeast',
      'Plant-Based Meat Crumbles',
      'Plant-Based Chicken',
      'Plant-Based Fish',
      'Plant-Based Shrimp',
      'Plant-Based Hot Dogs',
      'Plant-Based Deli Slices',
      'Plant-Based Jerky',
      'Plant-Based Meatballs',
      'Plant-Based Tacos',
      'Plant-Based Pizza',
      'Plant-Based Nuggets',
      'Plant-Based Ribs',
      'Plant-Based Steak',
      'Plant-Based Ground Beef',
      'Plant-Based Sausage Links',
    ],
    'Meats': [
      'Beef',
      'Pork',
      'Lamb',
      'Bacon',
      'Sausage',
      'Ground Beef',
      'Steak',
      'Ribs',
      'Brisket',
      'Roast',
      'Pork Chops',
      'Pork Tenderloin',
      'Pork Belly',
      'Lamb Chops',
      'Lamb Shank',
      'Lamb Shoulder',
      'Chicken',
      'Turkey',
      'Duck',
      'Goose',
      'Cornish Hen',
      'Chicken Breast',
      'Chicken Thighs',
      'Chicken Wings',
      'Chicken Drumsticks',
      'Ground Turkey',
      'Turkey Breast',
      'Turkey Legs',
      'Turkey Sausage',
      'Fish',
      'Salmon',
      'Tuna',
      'Shrimp',
      'Crab',
      'Cod',
      'Mussels',
      'Clams',
      'Oysters',
      'Scallops',
      'Tilapia',
      'Haddock',
      'Sardines',
      'Anchovies',
      'Mahi Mahi',
      'Snapper',
      'Trout',
      'Catfish',
      'Swordfish',
      'Halibut',
      'Bass',
      'Prawns',
      'Lobster',
      'Octopus',
      'Squid',
      'Crawfish',
      'Venison',
      'Bison',
      'Elk',
      'Rabbit',
      'Quail',
      'Frog Legs',
      'Wild Boar',
      'Kangaroo',
      'Pheasant',
      'Goat',
    ],
    'Poultry': [
      'Chicken',
      'Turkey',
      'Duck',
      'Goose',
      'Cornish Hen',
      'Chicken Breast',
      'Chicken Thighs',
      'Chicken Wings',
      'Chicken Drumsticks',
      'Ground Turkey',
      'Turkey Breast',
      'Turkey Legs',
      'Turkey Sausage',
      'Duck Breast',
      'Duck Legs',
      'Duck Wings',
      'Goose Breast',
      'Goose Legs',
      'Pheasant',
      'Quail',
      'Guinea Fowl',
      'Squab',
      'Bantam',
      'Capon',
      'Fried Chicken',
      'Roast Chicken',
      'Grilled Chicken',
      'Smoked Chicken',
      'Chicken Salad',
      'Chicken Soup',
      'Chicken Tacos',
      'Chicken Stir-Fry',
      'Chicken Curry',
      'Chicken Alfredo',
      'Chicken Parmesan',
      'Chicken Fajitas',
      'Chicken Pot Pie',
      'Turkey Burgers',
      'Turkey Meatballs',
      'Turkey Chili',
      'Turkey Stir-Fry',
      'Duck Confit',
      'Duck Curry',
      'Duck Salad',
      'Goose Stew',
      'Goose Ragu',
      'Pheasant Pot Pie',
      'Quail Eggs',
      'Quail Salad',
      'Guinea Fowl Stew',
      'Bantam Chicken',
      'Capon Roast',
      'Chicken Nuggets',
      'Chicken Skewers',
      'Chicken Katsu',
      'Chicken Satay',
      'Chicken Cacciatore',
      'Chicken Piccata',
      'Chicken Kiev',
      'Chicken Tenders',
      'Chicken Enchiladas',
      'Chicken Quesadillas',
    ],
    'Fish & Seafood': [
      'Salmon',
      'Tuna',
      'Shrimp',
      'Crab',
      'Cod',
      'Mussels',
      'Clams',
      'Oysters',
      'Scallops',
      'Tilapia',
      'Haddock',
      'Sardines',
      'Anchovies',
      'Mahi Mahi',
      'Snapper',
      'Trout',
      'Catfish',
      'Swordfish',
      'Halibut',
      'Bass',
      'Prawns',
      'Lobster',
      'Octopus',
      'Squid',
      'Crawfish',
      'Tuna Steaks',
      'Salmon Fillets',
      'Fish Tacos',
      'Fish Curry',
      'Fish and Chips',
      'Seafood Paella',
      'Seafood Risotto',
      'Seafood Pasta',
      'Seafood Chowder',
      'Seafood Salad',
      'Seafood Stir-Fry',
      'Seafood Ceviche',
      'Fish Cakes',
      'Fish Stew',
      'Fish Soup',
      'Fish Tacos',
      'Fish Sandwiches',
      'Fish Kebabs',
      'Fish Curry',
      'Fish Casserole',
      'Fish Pie',
      'Fish Fajitas',
      'Fish Tostadas',
      'Fish Tostadas',
      'Fish Burritos',
    ],
    'Herbs & Spices': [
      'Basil',
      'Oregano',
      'Cumin',
      'Cinnamon',
      'Paprika',
      'Thyme',
      'Rosemary',
      'Sage',
      'Dill',
      'Parsley',
      'Cilantro',
      'Chives',
      'Tarragon',
      'Bay Leaves',
      'Mint',
      'Fennel',
      'Marjoram',
      'Cardamom',
      'Ginger',
      'Turmeric',
      'Nutmeg',
      'Allspice',
      'Cloves',
      'Black Pepper',
      'White Pepper',
      'Red Pepper Flakes',
      'Chili Powder',
      'Curry Powder',
      'Garlic Powder',
      'Onion Powder',
      'Celery Salt',
      'Seasoned Salt',
      'Garlic Salt',
      'Herbes de Provence',
      'Italian Seasoning',
      'Chinese Five Spice',
      'Ras el Hanout',
      'Dried Thyme',
      'Dried Oregano',
      'Dried Basil',
      'Dried Rosemary',
      'Dried Dill',
      'Dried Parsley',
      'Dried Cilantro',
      'Dried Chives',
      'Dried Mint',
      'Dried Sage',
      'Dried Tarragon',
      'Dried Marjoram',
      'Dried Fennel',
      'Dried Bay Leaves',
      'Dried Ginger',
      'Dried Turmeric',
    ],
    'Sugar & Sweeteners': [
      'White Sugar',
      'Brown Sugar',
      'Honey',
      'Maple Syrup',
      'Stevia',
      'Agave Nectar',
      'Coconut Sugar',
      'Molasses',
      'Corn Syrup',
      'High Fructose Corn Syrup',
      'Powdered Sugar',
      'Confectioners Sugar',
      'Liquid Sweeteners',
      'Date Sugar',
      'Fruit Juice Concentrate',
      'Barley Malt Syrup',
      'Rice Syrup',
      'Sorghum Syrup',
      'Palm Sugar',
      'Malt Extract',
      'Maltose',
      'Xylitol',
      'Erythritol',
      'Monk Fruit Sweetener',
      'Aspartame',
      'Sucralose',
      'Saccharin',
      'Stevia Extract',
      'Agave Syrup',
      'Honey Crystals',
      'Maple Sugar',
      'Coconut Nectar',
      'Brown Rice Syrup',
      'Date Syrup',
      'Fruit Sweeteners',
      'Sweetened Condensed Milk',
      'Sweetened Coconut Flakes',
      'Sweetened Yogurt',
      'Sweetened Almond Milk',
      'Sweetened Soy Milk',
    ],
    'Seasonings & Spice Blends': [
      'Curry Powder',
      'Taco Seasoning',
      'Italian Seasoning',
      'Cajun Seasoning',
      'Chili Seasoning',
      'Garlic Salt',
      'Onion Salt',
      'Seasoned Salt',
      'Herbes de Provence',
      'Chinese Five Spice',
      'Ras el Hanout',
      'Garam Masala',
      'Jerk Seasoning',
      'Tandoori Spice',
      'Fajita Seasoning',
      'Cajun Spice',
      'Creole Seasoning',
      'Fish Seasoning',
      'Steak Seasoning',
      'Poultry Seasoning',
      'Barbecue Rub',
      'Smoked Paprika',
      'Sweet Paprika',
      'Cinnamon Sugar',
      'Pumpkin Pie Spice',
      'Apple Pie Spice',
      'Chili Powder',
      'Cajun Spice Mix',
      'Dried Herb Mix',
      'Savory Spice Blend',
      'Mediterranean Spice Blend',
      'Southwest Spice Blend',
      'Italian Herb Blend',
      'Greek Seasoning',
      'Baking Spice Blend',
      'Citrus Seasoning',
      'Spicy Seasoning',
      'Sweet and Spicy Seasoning',
      'Umami Seasoning',
      'Salt-Free Seasoning',
      'Vegetable Seasoning',
      'Fish and Seafood Seasoning',
      'Meat Seasoning',
      'Pasta Seasoning',
      'Rice Seasoning',
      'Salad Seasoning',
      'Soup Seasoning',
      'Stew Seasoning',
      'Casserole Seasoning',
      'Grill Seasoning',
      'Roasting Seasoning',
      'Sauté Seasoning',
      'Stir-Fry Seasoning',
    ],
    'Baking': [
      'Baking Powder',
      'Baking Soda',
      'Vanilla Extract',
      'Yeast',
      'Cocoa Powder',
      'Flour',
      'Sugar',
      'Brown Sugar',
      'Powdered Sugar',
      'Cornstarch',
      'Almond Flour',
      'Coconut Flour',
      'Whole Wheat Flour',
      'Bread Flour',
      'Cake Flour',
      'Self-Rising Flour',
      'Gluten-Free Flour',
      'Oat Flour',
      'Rice Flour',
      'Tapioca Flour',
      'Potato Flour',
      'Soy Flour',
      'Chickpea Flour',
      'Nut Flours',
      'Baking Chocolate',
      'Chocolate Chips',
      'White Chocolate Chips',
      'Butterscotch Chips',
      'Caramel Bits',
      'Dried Fruits',
      'Nuts',
      'Seeds',
      'Coconut Flakes',
      'Coconut Sugar',
      'Honey',
      'Maple Syrup',
      'Molasses',
      'Agave Nectar',
      'Sweetened Condensed Milk',
      'Evaporated Milk',
      'Cream Cheese',
      'Sour Cream',
      'Yogurt',
      'Eggs',
      'Milk',
      'Heavy Cream',
      'Butter',
      'Shortening',
      'Margarine',
      'Oil',
      'Nut Butters',
      'Fruit Purees',
      'Applesauce',
      'Pumpkin Puree',
      'Zucchini Puree',
      'Banana Puree',
      'Chocolate Syrup',
      'Caramel Sauce',
      'Frosting',
      'Icing',
      'Glaze',
      'Ganache',
      'Whipped Cream',
    ],
    'Pre-made Doughs & Wrappers': [
      'Pizza Dough',
      'Pie Crust',
      'Wonton Wrappers',
      'Phyllo Dough',
      'Puff Pastry',
      'Tortilla Dough',
      'Spring Roll Wrappers',
      'Dumpling Wrappers',
      'Gyoza Wrappers',
      'Pasta Sheets',
      'Lasagna Noodles',
      'Ravioli Dough',
      'Bread Dough',
      'Biscuit Dough',
      'Scone Dough',
      'Cookie Dough',
      'Pasta Dough',
      'Tart Shells',
      'Empanada Dough',
      'Calzone Dough',
      'Pasta Dough',
      'Focaccia Dough',
      'Challah Dough',
      'Bagel Dough',
      'Brioche Dough',
      'Croissant Dough',
      'Danish Dough',
      'Gluten-Free Pizza Dough',
      'Gluten-Free Pie Crust',
      'Gluten-Free Tortilla Dough',
      'Gluten-Free Dumpling Wrappers',
      'Gluten-Free Biscuit Dough',
      'Gluten-Free Cookie Dough',
      'Gluten-Free Bread Dough',
      'Gluten-Free Focaccia Dough',
      'Gluten-Free Bagel Dough',
      'Gluten-Free Croissant Dough',
      'Gluten-Free Danish Dough',
      'Gluten-Free Ravioli Dough',
      'Gluten-Free Empanada Dough',
      'Gluten-Free Calzone Dough',
    ],
    'Grains & Cereals': [
      'Oats',
      'Rice',
      'Couscous',
      'Farro',
      'Millet',
      'Buckwheat',
      'Amaranth',
      'Teff',
      'Sorghum',
      'Freekeh',
      'Wild Rice',
      'Brown Rice',
      'White Rice',
      'Jasmine Rice',
      'Basmati Rice',
      'Arborio Rice',
      'Risotto Rice',
      'Instant Oats',
      'Rolled Oats',
      'Steel-Cut Oats',
      'Granola',
      'Muesli',
      'Puffed Rice',
      'Rice Cakes',
      'Cornmeal',
      'Polenta',
      'Grits',
      'Cream of Wheat',
      'Semolina',
      'Rye',
      'Spelt',
      'Barley Flour',
      'Oat Flour',
      'Rice Flour',
      'Corn Flour',
      'Whole Wheat Flour',
      'Almond Flour',
      'Coconut Flour',
      'Chickpea Flour',
      'Quinoa Flour',
      'Buckwheat Flour',
      'Millet Flour',
      'Sorghum Flour',
      'Teff Flour',
      'Amaranth Flour',
      'Freekeh Flour',
      'Gluten-Free Flour',
      'Bread Flour',
      'Cake Flour',
      'Pastry Flour',
      'Self-Rising Flour',
      'All-Purpose Flour',
      'Pasta Flour',
      'Pizza Flour',
      'Baking Mix',
      'Pancake Mix',
      'Waffle Mix',
      'Dumpling Mix',
      'Biscuit Mix',
      'Scone Mix',
      'Cookie Mix',
      'Brownie Mix',
      'Cake Mix',
      'Muffin Mix',
      'Cornbread Mix',
      'Fried Rice Mix',
    ],
    'Legumes': [
      'Lentils',
      'Chickpeas',
      'Black Beans',
      'Kidney Beans',
      'Pinto Beans',
      'Navy Beans',
      'Great Northern Beans',
      'Cannellini Beans',
      'Adzuki Beans',
      'Mung Beans',
      'Split Peas',
      'Green Peas',
      'Yellow Peas',
      'Soybeans',
      'Edamame',
      'Fava Beans',
      'Borlotti Beans',
      'Pigeon Peas',
      'Lima Beans',
      'Black-eyed Peas',
      'Canned Beans',
      'Dried Beans',
      'Bean Sprouts',
      'Hummus',
      'Bean Dip',
      'Bean Salad',
      'Chili',
      'Bean Burgers',
      'Bean Tacos',
      'Bean Soup',
      'Bean Stew',
      'Bean Casserole',
      'Bean Salad',
      'Bean Chili',
      'Bean Quesadillas',
      'Bean Enchiladas',
      'Bean Burritos',
      'Bean Fritters',
      'Bean Patties',
      'Bean Cakes',
      'Bean Pasta',
      'Bean Flour',
      'Bean Protein Powder',
      'Bean Snacks',
      'Roasted Chickpeas',
      'Roasted Edamame',
      'Bean Chips',
    ],
    'Pasta': [
      'Spaghetti',
      'Penne',
      'Fettuccine',
      'Macaroni',
      'Lasagna Sheets',
      'Fusilli',
      'Rotini',
      'Orzo',
      'Ravioli',
      'Tortellini',
      'Pasta Shells',
      'Ziti',
      'Capellini',
      'Linguine',
      'Bucatini',
      'Pappardelle',
      'Cavatappi',
      'Gemelli',
      'Orecchiette',
      'Fideo',
      'Soba Noodles',
      'Udon Noodles',
      'Rice Noodles',
      'Egg Noodles',
      'Whole Wheat Pasta',
      'Gluten-Free Pasta',
      'Chickpea Pasta',
      'Lentil Pasta',
      'Quinoa Pasta',
      'Brown Rice Pasta',
      'Zucchini Noodles',
      'Spaghetti Squash',
      'Pasta Sauce',
      'Pasta Salad',
      'Pasta Bake',
      'Pasta Primavera',
      'Pasta Carbonara',
      'Pasta Alfredo',
      'Pasta Puttanesca',
      'Pasta Bolognese',
      'Pasta Arrabbiata',
      'Pasta with Pesto',
      'Pasta with Marinara',
      'Pasta with Meatballs',
    ],
    'Bread & Salty Snacks': [
      'Bread',
      'Crackers',
      'Pretzels',
      'Tortilla Chips',
      'Popcorn',
      'Rice Cakes',
      'Pita Bread',
      'Bagels',
      'English Muffins',
      'Flatbreads',
      'Naan',
      'Focaccia',
      'Ciabatta',
      'Sourdough',
      'Whole Wheat Bread',
      'Rye Bread',
      'Multigrain Bread',
      'Gluten-Free Bread',
      'Biscotti',
      'Breadsticks',
      'Cheese Sticks',
      'Garlic Bread',
      'Croutons',
      'Bread Pudding',
      'Savory Scones',
      'Savory Muffins',
      'Cheese Puffs',
      'Cheese Crisps',
      'Cheese Straws',
      'Cheese Crackers',
      'Savory Granola',
      'Savory Trail Mix',
      'Savory Popcorn',
      'Savory Rice Cakes',
      'Savory Tortilla Chips',
      'Savory Pita Chips',
      'Savory Flatbreads',
      'Savory Waffles',
      'Savory Pancakes',
      'Savory Crepes',
      'Savory Tarts',
      'Savory Quiches',
      'Savory Fritters',
      'Savory Cakes',
      'Savory Breads',
      'Savory Rolls',
      'Savory Biscuits',
      'Savory Doughnuts',
      'Savory Bagels',
      'Savory Pretzel Bites',
      'Savory Cheese Balls',
      'Savory Cheese Dip',
      'Savory Cheese Spread',
      'Savory Cheese Fondue',
    ],
    'Oils & Fats': [
      'Vegetable Oil',
      'Coconut Oil',
      'Butter',
      'Olive Oil',
      'Sesame Oil',
      'Canola Oil',
      'Sunflower Oil',
      'Peanut Oil',
      'Avocado Oil',
      'Grapeseed Oil',
      'Flaxseed Oil',
      'Hemp Oil',
      'Walnut Oil',
      'Almond Oil',
      'Macadamia Oil',
      'Pumpkin Seed Oil',
      'Safflower Oil',
      'Soybean Oil',
      'Corn Oil',
      'Lard',
      'Tallow',
      'Ghee',
      'Clarified Butter',
      'Margarine',
      'Shortening',
      'Coconut Cream',
      'Coconut Milk',
      'Nut Butters',
      'Peanut Butter',
      'Almond Butter',
      'Cashew Butter',
      'Sunflower Seed Butter',
      'Tahini',
      'Nut Oils',
      'Flavored Oils',
      'Infused Oils',
      'Herb Oils',
      'Chili Oil',
      'Garlic Oil',
      'Truffle Oil',
      'Balsamic Glaze',
      'Vinegar',
      'Cooking Wine',
      'Rice Vinegar',
      'Apple Cider Vinegar',
    ],
    'Dressings & Vinegars': [
      'Balsamic Vinegar',
      'Ranch Dressing',
      'Italian Dressing',
      'Apple Cider Vinegar',
      'Red Wine Vinegar',
      'White Wine Vinegar',
      'Rice Vinegar',
      'Malt Vinegar',
      'Champagne Vinegar',
      'Cider Vinegar',
      'Herb Vinaigrette',
      'Honey Mustard Dressing',
      'Caesar Dressing',
      'Blue Cheese Dressing',
      'Thousand Island Dressing',
      'Greek Dressing',
      'Asian Sesame Dressing',
      'Cilantro Lime Dressing',
      'Avocado Dressing',
      'Creamy Garlic Dressing',
      'Lemon Vinaigrette',
      'Mustard Vinaigrette',
      'Maple Vinaigrette',
      'Peanut Dressing',
      'Tahini Dressing',
      'Soy Sauce',
      'Teriyaki Sauce',
      'Barbecue Sauce',
      'Hot Sauce',
      'Sriracha',
      'Chili Sauce',
      'Sweet and Sour Sauce',
      'Soy Ginger Dressing',
      'Coconut Aminos',
      'Fish Sauce',
      'Worcestershire Sauce',
      'Steak Sauce',
      'Tartar Sauce',
      'Remoulade',
      'Chimichurri',
      'Pesto',
      'Salsa',
      'Guacamole',
      'Hummus',
      'Tzatziki',
    ],
    'Condiments': [
      'Ketchup',
      'Mustard',
      'Mayonnaise',
      'Soy Sauce',
      'Hot Sauce',
      'Sriracha',
      'Barbecue Sauce',
      'Relish',
      'Chili Sauce',
      'Tartar Sauce',
      'Worcestershire Sauce',
      'Steak Sauce',
      'Fish Sauce',
      'Teriyaki Sauce',
      'Sweet and Sour Sauce',
      'Honey',
      'Maple Syrup',
      'Peanut Butter',
      'Nutella',
      'Hummus',
      'Guacamole',
      'Salsa',
      'Pesto',
      'Chimichurri',
      'Tahini',
      'Coconut Aminos',
      'Miso Paste',
      'Tomato Paste',
      'Curry Paste',
      'Harissa',
      'Dijon Mustard',
      'Yellow Mustard',
      'Spicy Mustard',
      'Honey Mustard',
      'Whole Grain Mustard',
      'Garlic Aioli',
      'Chipotle Aioli',
      'Ranch Dressing',
      'Blue Cheese Dressing',
      'Caesar Dressing',
      'Italian Dressing',
      'Vegan Mayo',
      'Vegan Cheese',
      'Vegan Sour Cream',
      'Vegan Cream Cheese',
      'Vegan Ranch',
      'Vegan Caesar',
      'Vegan Thousand Island',
      'Vegan BBQ Sauce',
      'Vegan Teriyaki Sauce',
      'Vegan Hot Sauce',
      'Vegan Ketchup',
      'Vegan Mustard',
      'Vegan Salsa',
      'Vegan Pesto',
      'Vegan Guacamole',
      'Vegan Hummus',
      'Vegan Tzatziki',
      'Vegan Aioli',
      'Vegan Relish',
      'Vegan Chili Sauce',
      'Vegan Soy Sauce',
      'Vegan Worcestershire Sauce',
      'Vegan Fish Sauce',
      'Vegan Steak Sauce',
      'Vegan Sweet and Sour Sauce',
      'Vegan Miso',
      'Vegan Tomato Paste',
      'Vegan Curry Paste',
      'Vegan Harissa',
      'Vegan Hot Pepper Sauce',
      'Vegan Garlic Sauce',
      'Vegan Ginger Sauce',
      'Vegan Teriyaki Marinade',
      'Vegan Marinara Sauce',
      'Vegan Alfredo Sauce',
      'Vegan Creamy Dressing',
      'Vegan Spicy Dressing',
      'Vegan Sweet Dressing',
      'Vegan Savory Dressing',
    ],
    'Canned Food': [
      'Canned Tomatoes',
      'Canned Beans',
      'Canned Tuna',
      'Canned Corn',
      'Canned Soup',
      'Canned Vegetables',
      'Canned Fruit',
      'Canned Coconut Milk',
      'Canned Pumpkin',
      'Canned Peas',
      'Canned Mushrooms',
      'Canned Artichokes',
      'Canned Olives',
      'Canned Peppers',
      'Canned Chili',
      'Canned Sauerkraut',
      'Canned Kimchi',
      'Canned Sauces',
      'Canned Broth',
      'Canned Stock',
      'Canned Fish',
      'Canned Chicken',
      'Canned Beef',
      'Canned Pork',
      'Canned Seafood',
      'Canned Fruit Cocktail',
      'Canned Pineapple',
      'Canned Peaches',
      'Canned Pears',
      'Canned Apples',
      'Canned Cherries',
      'Canned Cranberries',
      'Canned Jams',
      'Canned Preserves',
      'Canned Sauces',
      'Canned Salsas',
      'Canned Dips',
      'Canned Spaghetti',
      'Canned Ravioli',
      'Canned Chili Beans',
      'Canned Refried Beans',
      'Canned Black Beans',
      'Canned Kidney Beans',
      'Canned Lentils',
      'Canned Chickpeas',
      'Canned Split Peas',
    ],
    'Sauces, Spreads & Dips': [
      'Pasta Sauce',
      'Hummus',
      'Peanut Butter',
      'Alfredo Sauce',
      'Tahini',
      'Guacamole',
      'Salsa',
      'Pesto',
      'Chimichurri',
      'Barbecue Sauce',
      'Hot Sauce',
      'Soy Sauce',
      'Teriyaki Sauce',
      'Sweet and Sour Sauce',
      'Ranch Dressing',
      'Blue Cheese Dressing',
      'Caesar Dressing',
      'Italian Dressing',
      'Vegan Mayo',
      'Vegan Cream Cheese',
      'Vegan Hummus',
      'Vegan Guacamole',
      'Vegan Salsa',
      'Vegan Pesto',
      'Vegan Tahini',
      'Vegan Alfredo',
      'Vegan BBQ Sauce',
      'Vegan Teriyaki',
      'Vegan Sweet and Sour',
      'Vegan Ranch',
      'Vegan Caesar',
      'Vegan Thousand Island',
      'Vegan Chipotle Sauce',
      'Vegan Garlic Sauce',
      'Vegan Ginger Sauce',
      'Vegan Curry Sauce',
      'Vegan Tomato Sauce',
      'Vegan Marinara',
      'Vegan Spicy Sauce',
      'Vegan Savory Sauce',
      'Vegan Sweet Sauce',
      'Vegan Creamy Sauce',
      'Vegan Spicy Mayo',
      'Vegan Garlic Aioli',
      'Vegan Chipotle Aioli',
      'Vegan Tzatziki',
      'Vegan Ranch Dip',
      'Vegan Spinach Dip',
      'Vegan Artichoke Dip',
      'Vegan Cheese Dip',
      'Vegan Bean Dip',
    ],
    'Soups, Stews & Stocks': [
      'Chicken Stock',
      'Beef Stock',
      'Vegetable Broth',
      'Tomato Soup',
      'Lentil Soup',
      'Minestrone',
      'Chili',
      'Split Pea Soup',
      'Mushroom Soup',
      'Cream of Mushroom',
      'Chicken Noodle Soup',
      'Beef Stew',
      'Vegetable Soup',
      'Clam Chowder',
      'Corn Chowder',
      'Potato Soup',
      'Broccoli Cheddar Soup',
      'French Onion Soup',
      'Tom Yum Soup',
      'Miso Soup',
      'Gazpacho',
      'Butternut Squash Soup',
      'Pumpkin Soup',
      'Carrot Ginger Soup',
      'Sweet Potato Soup',
      'Cabbage Soup',
      'Split Pea Soup',
      'Beef Barley Soup',
      'Chicken Tortilla Soup',
      'Sausage and Kale Soup',
      'Italian Wedding Soup',
      'Egg Drop Soup',
      'Hot and Sour Soup',
      'Vegetable Beef Soup',
      'Creamy Tomato Basil Soup',
      'Lentil and Spinach Soup',
      'Coconut Curry Soup',
      'Spicy Black Bean Soup',
      'Creamy Potato Leek Soup',
      'Roasted Red Pepper Soup',
      'Zucchini Soup',
      'Chickpea Soup',
      'Seafood Chowder',
      'Clam Chowder',
      'Fish Chowder',
      'Vegetable Stock',
      'Chicken Broth',
      'Beef Broth',
      'Fish Stock',
      'Mushroom Broth',
      'Bone Broth',
      'Dashi',
      'Ramen Broth',
      'Pho Broth',
      'Tom Yum Broth',
      'Vegetable Bouillon',
      'Chicken Bouillon',
      'Beef Bouillon',
      'Mushroom Bouillon',
      'Seafood Bouillon',
      'Herb Bouillon',
    ],
    'Desserts & Sweet Snacks': [
      'Chocolate',
      'Cookies',
      'Ice Cream',
      'Cake Mix',
      'Brownie Mix',
      'Pudding',
      'Gelatin',
      'Custard',
      'Cheesecake',
      'Tarts',
      'Pies',
      'Cobbler',
      'Crumbles',
      'Muffins',
      'Doughnuts',
      'Cupcakes',
      'Pancakes',
      'Waffles',
      'Crepes',
      'Pavlova',
      'Tiramisu',
      'Baklava',
      'Macarons',
      'Truffles',
      'Fudge',
      'Marshmallows',
      'Candy',
      'Gummy Bears',
      'Chocolate Bars',
      'Chocolate Chips',
      'Chocolate Syrup',
      'Caramel Sauce',
      'Whipped Cream',
      'Frosting',
      'Icing',
      'Ganache',
      'Fruit Salad',
      'Fruit Parfait',
      'Fruit Tart',
      'Fruit Sorbet',
      'Fruit Popsicles',
      'Fruit Smoothies',
      'Fruit Cups',
      'Fruit Cups',
      'Fruit Leather',
      'Fruit Chips',
      'Fruit Roll-Ups',
      'Fruit Snacks',
      'Fruit Jellies',
      'Fruit Preserves',
      'Fruit Compote',
      'Fruit Crumble',
      'Fruit Crust',
      'Fruit Cake',
      'Fruit Bread',
      'Fruit Muffins',
      'Fruit Pudding',
      'Fruit Sorbet',
      'Fruit Gelato',
    ],
    'Wine, Beer & Spirits': [
      'Red Wine',
      'White Wine',
      'Beer',
      'Vodka',
      'Whiskey',
      'Rum',
      'Tequila',
      'Gin',
      'Champagne',
      'Sparkling Wine',
      'Port',
      'Sherry',
      'Cider',
      'Sake',
      'Mead',
      'Absinthe',
      'Liqueurs',
      'Bitters',
      'Cocktail Mixers',
      'Vermouth',
      'Aperitif',
      'Digestif',
      'Sangria',
      'Mimosas',
      'Bellinis',
      'Spritzers',
      'Fruity Cocktails',
      'Frozen Cocktails',
      'Classic Cocktails',
      'Craft Beer',
      'IPA',
      'Stout',
      'Porter',
      'Pilsner',
      'Lager',
      'Sour Beer',
      'Wheat Beer',
      'Belgian Beer',
      'Cider',
      'Hard Seltzer',
      'Hard Lemonade',
      'Hard Tea',
      'Non-Alcoholic Beer',
      'Non-Alcoholic Wine',
      'Non-Alcoholic Spirits',
      'Mocktails',
      'Virgin Cocktails',
      'Alcohol-Free Wine',
      'Alcohol-Free Spirits',
      'Alcohol-Free Beer',
    ],
    'Beverages': [
      'Coffee',
      'Tea',
      'Juice',
      'Soda',
      'Sparkling Water',
      'Mineral Water',
      'Flavored Water',
      'Herbal Tea',
      'Green Tea',
      'Black Tea',
      'White Tea',
      'Oolong Tea',
      'Chai',
      'Matcha',
      'Lemonade',
      'Iced Tea',
      'Iced Coffee',
      'Smoothies',
      'Protein Shakes',
      'Meal Replacement Shakes',
      'Energy Drinks',
      'Sports Drinks',
      'Coconut Water',
      'Almond Milk',
      'Soy Milk',
      'Oat Milk',
      'Rice Milk',
      'Hemp Milk',
      'Cashew Milk',
      'Flax Milk',
      'Pea Milk',
      'Macadamia Milk',
      'Chocolate Milk',
      'Coffee Creamer',
      'Non-Dairy Creamer',
      'Fruit Smoothies',
      'Vegetable Juices',
      'Nut Milk',
      'Coconut Milk',
      'Kefir',
      'Aloe Vera Juice',
      'Tonic Water',
      'Sparkling Juice',
      'Fruit Punch',
      'Lemonade',
      'Iced Coffee',
      'Iced Tea',
      'Herbal Infusions',
      'Flavored Teas',
      'Chai Latte',
      'Matcha Latte',
      'Golden Milk',
      'Turmeric Latte',
      'Cacao Drinks',
      'Hot Chocolate',
      'Milkshakes',
      'Frappes',
      'Frappe Coffee',
      'Bubble Tea',
      'Boba Tea',
      'Smoothie Bowls',
      'Protein Smoothies',
      'Meal Replacement Drinks',
      'Detox Water',
      'Infused Water',
      'Herbal Tonics',
      'Cold Brew Coffee',
      'Nitro Coffee',
      'Espresso',
      'Cappuccino',
      'Latte',
      'Macchiato',
      'Affogato',
      'Flat White',
      'Ristretto',
      'Café au Lait',
      'Turkish Coffee',
      'Vietnamese Coffee',
      'Dalgona Coffee',
      'Coffee Cocktails',
      'Coffee Syrups',
      'Coffee Creamers',
      'Coffee Pods',
      'Coffee Beans',
      'Coffee Grounds',
      'Instant Coffee',
      'Decaf Coffee',
      'Coffee Blends',
      'Coffee Flavors',
      'Coffee Extracts',
      'Coffee Concentrates',
      'Coffee Mixes',
      'Coffee Substitutes',
      'Chicory Coffee',
      'Roasted Barley Coffee',
      'Dandelion Coffee',
      'Cereal Coffee',
      'Mushroom Coffee',
      'Herbal Coffee',
      'Caffeine-Free Drinks',
    ],
    'Supplements & Extracts': [
      'Protein Powder',
      'Vitamin C',
      'Vanilla Extract',
      'Fish Oil',
      'Probiotics',
      'Prebiotics',
      'Omega-3',
      'Omega-6',
      'Omega-9',
      'Flaxseed Oil',
      'Chia Seed Oil',
      'Evening Primrose Oil',
      'Borage Oil',
      'Krill Oil',
      'Cod Liver Oil',
      'MCT Oil',
      'Coconut Oil',
      'Hemp Oil',
      'Pumpkin Seed Oil',
      'Sunflower Seed Oil',
      'Almond Oil',
      'Walnut Oil',
      'Grapeseed Oil',
      'Rice Bran Oil',
      'Avocado Oil',
      'Sesame Oil',
      'Beetroot Powder',
      'Spirulina',
      'Chlorella',
      'Maca Powder',
      'Acai Powder',
      'Cacao Powder',
      'Matcha Powder',
      'Turmeric Powder',
      'Ginger Powder',
      'Cinnamon Powder',
      'Garlic Powder',
      'Onion Powder',
      'Cayenne Pepper',
      'Chili Powder',
      'Curry Powder',
      'Herbal Extracts',
      'Green Tea Extract',
      'Ginseng',
      'Ashwagandha',
      'Rhodiola',
      'Moringa',
      'Aloe Vera',
      'Elderberry',
      'Echinacea',
      'Milk Thistle',
      'Dandelion Root',
      'Ginger Root',
      'Turmeric Root',
      'Garlic',
      'Onion',
      'Cinnamon',
      'Cloves',
      'Nutmeg',
      'Cardamom',
      'Fennel',
      'Thyme',
      'Rosemary',
      'Sage',
      'Basil',
      'Oregano',
      'Parsley',
      'Cilantro',
      'Chives',
      'Dill',
      'Tarragon',
      'Marjoram',
      'Bay Leaves',
      'Lemon Balm',
      'Peppermint',
      'Spearmint',
      'Lemongrass',
      'Chamomile',
      'Lavender',
      'Hibiscus',
      'Rooibos',
      'Yerba Mate',
    ],
  };

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: _categories.length, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Select Ingredients'),
        backgroundColor: Colors.deepOrange,
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(100.0),
          child: Container(
            color: Colors.orange[50],
            child: Column(
              children: [
                TabBar(
                  controller: _tabController,
                  isScrollable: true,
                  indicatorColor: Colors.deepOrange,
                  labelColor: Colors.deepOrange,
                  unselectedLabelColor: Colors.grey,
                  tabs: _categories.map((category) => Tab(
                    child: Container(
                      padding: EdgeInsets.symmetric(horizontal: 16),
                      height: 50,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(50),
                        color: Colors.white,
                      ),
                      child: Center( // Centering the content vertically
                        child: Text(
                          category,
                          style: TextStyle(fontWeight: FontWeight.w900),
                        ),
                      ),
                    ),
                  )).toList(),
                ),
                Padding(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 16.0,
                    vertical: 8,
                  ),
                  child: TextField(
                    controller: _searchController,
                    decoration: InputDecoration(
                      hintText: 'Search ingredients...',
                      prefixIcon: Icon(Icons.search, color: Colors.deepOrange),
                      filled: true,
                      fillColor: Colors.white,
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(30),
                        borderSide: BorderSide.none,
                      ),
                      contentPadding: EdgeInsets.symmetric(
                        vertical: 0,
                        horizontal: 20,
                      ),
                    ),
                    onChanged: (value) {
                      setState(() {
                        _searchQuery = value.toLowerCase();
                      });
                    },
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children:
            _categories.map((category) {
              return _buildIngredientList(category);
            }).toList(),
      ),
      floatingActionButton:
          _selectedIngredients.isNotEmpty
              ? FloatingActionButton.extended(
                onPressed: () async {
                  try {
                    final recipes =
                        await RecipeService.findRecipesByIngredients(
                          _selectedIngredients.toList(),
                        );
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder:
                            (context) => Scaffold(
                              appBar: AppBar(
                                title: const Text('Recipes'),
                                backgroundColor: Colors.deepOrange,
                              ),
                              body: ListView.builder(
                                itemCount: recipes.length,
                                itemBuilder: (context, index) {
                                  final recipe = recipes[index];
                                  return Card(
                                    margin: EdgeInsets.symmetric(
                                      horizontal: 16,
                                      vertical: 8,
                                    ),
                                    elevation: 3,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                    child: ListTile(
                                      leading:
                                          recipe['image'] != null
                                              ? ClipRRect(
                                                borderRadius:
                                                    BorderRadius.circular(8),
                                                child: Image.network(
                                                  recipe['image'],
                                                  width: 50,
                                                  height: 50,
                                                  fit: BoxFit.cover,
                                                ),
                                              )
                                              : null,
                                      title: Text(
                                        recipe['title'],
                                        style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                        ),
                                      ),
                                      subtitle: Text(
                                        'Uses ${recipe['usedIngredientCount']} of your ingredients',
                                        style: TextStyle(
                                          color: Colors.deepOrange,
                                        ),
                                      ),
                                      trailing: Icon(
                                        Icons.chevron_right,
                                        color: Colors.deepOrange,
                                      ),
                                      onTap: () {
                                        Navigator.push(
                                          context,
                                          MaterialPageRoute(
                                            builder:
                                                (context) =>
                                                    RecipeDetailsScreen(
                                                      recipeId: recipe['id'],
                                                      recipeTitle:
                                                          recipe['title'],
                                                    ),
                                          ),
                                        );
                                      },
                                    ),
                                  );
                                },
                              ),
                            ),
                      ),
                    );
                  } catch (e) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: Text('Error: $e'),
                        backgroundColor: Colors.red,
                      ),
                    );
                  }
                },
                label: const Text(
                  'Find Recipes',
                          style: TextStyle(fontWeight: FontWeight.bold, color: Colors.black),
                ),
                icon: const Icon(Icons.search),
                backgroundColor: Colors.deepOrange,
              )
              : null,
    );
  }

  Widget _buildIngredientList(String category) {
    final filteredIngredients =
        _categoryIngredients[category]!
            .where(
              (ingredient) => ingredient.toLowerCase().contains(_searchQuery),
            )
            .toList();

    return ListView.builder(
      itemCount: filteredIngredients.length,
      itemBuilder: (context, index) {
        final ingredient = filteredIngredients[index];
        return Card(
          margin: EdgeInsets.symmetric(horizontal: 16, vertical: 4),
          elevation: 1,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10),
          ),
          child: CheckboxListTile(
            title: Text(ingredient, style: TextStyle(fontSize: 16)),
            value: _selectedIngredients.contains(ingredient),
            onChanged: (bool? value) {
              setState(() {
                if (value == true) {
                  _selectedIngredients.add(ingredient);
                } else {
                  _selectedIngredients.remove(ingredient);
                }
              });
            },
            activeColor: Colors.deepOrange,
            checkColor: Colors.white,
            controlAffinity: ListTileControlAffinity.leading,
            contentPadding: EdgeInsets.symmetric(horizontal: 16),
          ),
        );
      },
    );
  }
}
